#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include <wchar.h>
#include <boost/filesystem.hpp>
#include <vector>
#include <ctime>
#include <new> 

namespace fs = boost::filesystem;

void DateiVerarbeiten(fs::path pfad, std::ofstream& os);
void printLicense(void);

int main(int argc, char** argv)
{
	system("chcp 1252");
	system("cls");
	
	std::printf("\n.: (c)Ru:bensoft 2024 - pdfMergePrep :.\n\n");

	if(argc <2)
	{
		std::cout<<"\nVerwendung: pdfMergePrep.exe Datei_1 Datei_2 ...\n\n";
		std::cout<<"Entfernt Punkte aus dem Dateinamen (Datei_1 Datei_2 ...)\n";
		std::cout<<"und schreibt den '\\includepdf'-Block (LaTeX) fU:r jede Datei.\n\n";
		system("PAUSE");
		printLicense();
		system("PAUSE");
		return 1;
	}

	std::ofstream os("pdfMerge.tex", std::ios::out);
	if(!os.good())return 1;
	for(int datNr = 1; datNr < argc; datNr++)
	{
		fs::path pfad(argv[datNr]);
		if(!fs::exists(pfad))continue;
		if(!fs::is_regular_file(pfad))continue;

		fs::path subPfad = pfad.parent_path();
		if(fs::is_regular_file(pfad))
		{
			DateiVerarbeiten(pfad, os);
		}
	}
	os.close();
	system("PAUSE");
	return 0;
}

void DateiVerarbeiten(fs::path pfad, std::ofstream& os)
{
	std::string strPfad = pfad.filename().generic_string();
	std::cout<<"Suche in: "<<strPfad<<"\n";
	size_t letzteFundStelle = strPfad.find_last_of('.', std::string::npos);
	if(letzteFundStelle == std::string::npos)return;
	
	size_t fundStelle = 0;
	int gefunden = 0;
	do
	{
		fundStelle = strPfad.find('.', fundStelle+1);
		if(fundStelle != letzteFundStelle)
		{
			std::cout<<fundStelle<<" ";
			strPfad[fundStelle] = '_';
			gefunden++;
		}
	}while(fundStelle != letzteFundStelle);
	std::cout<<gefunden<<" Punkte gefunden\n\n";
	
	os<<"\\includepdf[\n";
	os<<"\tpages=-\n\taddtotoc={\t\n\t}\n]{"<<strPfad<<"}\n\n";
	
	return;
}

void printLicense(void)
{
	std::cout<<"\n*\t*\t*\t*\t*\n";
	std::cout<<"GNU GENERAL PUBLIC LICENSE disclaimer:\n\n";
	std::cout<<"This program is free software: you can redistribute it and/or modify\n";
	std::cout<<"it under the terms of the GNU General Public License as published by\n";
	std::cout<<"the Free Software Foundation, either version 3 of the License, or\n";
	std::cout<<"(at your option) any later version.\n\n";
	std::cout<<"This program is distributed in the hope that it will be useful,\n";
	std::cout<<"but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
	std::cout<<"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n";
	std::cout<<"GNU General Public License for more details.\n\n";
	std::cout<<"You should have received a copy of the GNU General Public License\n";
	std::cout<<"along with this program.  If not, see <http://www.gnu.org/licenses/>\n\n";
	std::cout<<"\n*\t*\t*\t*\t*\n";

	std::cout<<"Boost Software License - Version 1.0 - August 17th, 2003\n";
	std::cout<<"\n";
	std::cout<<"Permission is hereby granted, free of charge, to any person or organization\n";
	std::cout<<"obtaining a copy of the software and accompanying documentation covered by\n";
	std::cout<<"this license (the \"Software\") to use, reproduce, display, distribute,\n";
	std::cout<<"execute, and transmit the Software, and to prepare derivative works of the\n";
	std::cout<<"Software, and to permit third-parties to whom the Software is furnished to\n";
	std::cout<<"do so, all subject to the following:\n";
	std::cout<<"\n";
	std::cout<<"The copyright notices in the Software and this entire statement, including\n";
	std::cout<<"the above license grant, this restriction and the following disclaimer,\n";
	std::cout<<"must be included in all copies of the Software, in whole or in part, and\n";
	std::cout<<"all derivative works of the Software, unless such copies or derivative\n";
	std::cout<<"works are solely in the form of machine-executable object code generated by\n";
	std::cout<<"a source language processor.\n";
	std::cout<<"\n";
	std::cout<<"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n";
	std::cout<<"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n";
	std::cout<<"FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n";
	std::cout<<"SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n";
	std::cout<<"FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n";
	std::cout<<"ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n";
	std::cout<<"DEALINGS IN THE SOFTWARE.\n";
	std::cout<<"\n*\t*\t*\t*\t*\n";
	
	std::cout<<"Please find the licenses in the \"lic\"-folder\n\n";
	return;
}